import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yoga-club-profile",
  description: "Generated by create next app",
};

export default async function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center justify-between border-[1px] border-orange-300">
      <div>Common profile data</div>
      {children}
    </div>
  );
}
