import type { Metadata } from "next";
import { Inter, Philosopher, Mulish } from "next/font/google";

import { LocaleT, i18nConfig } from "@/i18nConfig";
import { dir } from "i18next";
import initTranslations from "./i18n";
import { Toaster } from "react-hot-toast";

import { TranslationsProvider } from "@/components/TranslationsProvider";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import Header from "@/sections/Header/Header";
import Header2 from "@/sections/Header2/Header2";
import Footer from "@/sections/Footer/Footer";

import "./globals.css";
import Footer2 from "@/sections/Footer2/Footer2";
import ButtonToTop from "@/components/ButtonToTop/ButtonToTop";

const inter = Inter({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-inter",
  subsets: ["cyrillic", "latin"],
});

const mulish = Mulish({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-mulish",
  subsets: ["cyrillic", "latin"],
});

const philosopher = Philosopher({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-philosopher",
  subsets: ["cyrillic", "latin"],
});

const i18nNamespaces = ["homePage", "eventsPage"];

export const metadata: Metadata = {
  title: "Yoga-club",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: LocaleT };
}) {
  const { t, resources } = await initTranslations(lang, i18nNamespaces);

  return (
    <html lang={lang} dir={dir(lang)}>
      <TranslationsProvider
        namespaces={i18nNamespaces}
        locale={lang}
        resources={resources}
      >
        <body
          className={`${inter.variable} ${mulish.variable} ${philosopher.variable} relative`}
        >
          <MySessionProvider>
            {/* <Header lang={lang} /> */}
            <Header2 lang={lang} />

            <main className="flex flex-col items-center justify-between font-mulish ">
              {children}
            </main>
            <Footer2 />

            {/* <Footer /> */}

            <div id="modal" />
            <Toaster />
            <ButtonToTop />
          </MySessionProvider>
        </body>
      </TranslationsProvider>
    </html>
  );
}
