import type { Metadata } from "next";
import { Inter, Philosopher, Mulish } from "next/font/google";

import { LocaleT, i18nConfig } from "@/i18nConfig";
import { dir } from "i18next";
import initTranslations from "./i18n";

// import TranslationsProvider from "@/components/TranslationsProvider";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import Header from "@/sections/Header/Header";
import Footer from "@/sections/Footer/Footer";

import "./globals.css";

const inter = Inter({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-inter",
  subsets: ["cyrillic", "latin"],
});

const mulish = Mulish({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-mulish",
  subsets: ["cyrillic", "latin"],
});

const philosopher = Philosopher({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-philosopher",
  subsets: ["cyrillic", "latin"],
});

const i18nNamespaces = ["homePage", "eventsPage"];

export const metadata: Metadata = {
  title: "Yoga-club",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: LocaleT };
}) {
  const { t, resources } = await initTranslations(lang, i18nNamespaces);

  return (
    <html lang={lang} dir={dir(lang)}>
      {/* <TranslationsProvider
        namespaces={i18nNamespaces}
        locale={lang}
        resources={resources}
      > */}
      <body
        className={`${inter.variable} ${mulish.variable} ${philosopher.variable}`}
      >
        <MySessionProvider>
          <Header lang={lang} />
          <main className="flex flex-col items-center justify-between">
            {children}
          </main>
          <Footer />
          <div id="modal" />
        </MySessionProvider>
      </body>
      {/* </TranslationsProvider> */}
    </html>
  );
}
